### ISSUE TITLE
vscode and atom editor expect the namespace to be all caps: 'AFRAME' not 'AFrame'

### ISSUE THREAD

**Issue by vt5491** [devpaul/aframe-typings#1]
As currently implemented, with Atom editor and vscode, your typings file will only generate auto-completions using 'Aframe' and not on 'AFRAME'.  In the following image note how 'AFRAME" is red lined, but 'AFrame' isn't:

![image](https://cloud.githubusercontent.com/assets/8662470/25414082/302fc58e-29e4-11e7-9cdb-501e8321b3bf.png)

The proper namespace is 'AFRAME', and while I personally prefer 'AFrame' over 'AFRAME' (less shouty), if you cut and paste examples off the web, they'll be using 'AFRAME' so for better or worse that's the namespace, just like it's 'THREE' for three.js.

I see that at the end you you have:
`declare const AFRAME: AFrame.AframeFramework;`

Which I think is an attempt to allow 'AFRAME' to be used.  But vscode says 'namespace not found' , and atom just won't auto-complete when using 'AFRAME'.  I think it's because they only recognize 'AFRAME' as a const and not as a namespace type.  

I had to make the following changes to 'AFRAME.d.ts' in order to get these editors to work with 'AFRAME'

 ```
//declare namespace AFrame {   <- original line 1
 declare namespace AFRAME {     <- new
```

and at the very bottom:
`//declare const AFRAME: AFrame.AframeFramework;   <- comment out`

I made a feeble attempt at trying to make the const work as a namespace:

`declare const namespace AFRAME: AFrame.AframeFramework;`

But this was not successful.

**Comment by vt5491** [comment]
ok..hmm.  I had to revert back to the original.  It looks you have to use the 'AFrame' form for the types, but 'AFRAME' for the functions (?)  For instance, this would *not* work until I reverted to the original:

```
    AFRAME.registerComponent('listener', {
      tick: function () {
        console.log(this.el.getAttribute('position'));
      }
    });
```

but when declaring types with original you have to specify it like this:

 `myEntity: AFrame.Entity`

So it's a little more a more subtle than I thought.  I guess my only question is "is this intentional"?  It seems odd that you wouldn't use 'AFRAME' when specifying types.  Feel free to close this if this is how it's supposed to be.  

Thanks,

**Comment by devpaul** [comment]
Hi @vt5491, Thanks for your feedback. One of the challenges in working with code that loads globally rather than via a loader is properly loading types. The easiest way is to simply bundle all of these types in a namespace so they're available globally as well, but don't collide with other definitions.

I've submitted a PR to DefinitelyTyped/DefinitelyTyped#16987 with these typings, so it'll be more open to the community to improve.
